Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('article.urls')),
    path('admin/', admin.site.urls),
]

django_docker/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('article.urls')),
    path('admin/', admin.site.urls),
]

django_docker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('article.urls')),
    path('admin/', admin.site.urls),
]

urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('article.urls')),
    path('admin/', admin.site.urls),
]

django_docker/article/models.py
from django.db import models


class Article(models.Model):
    create_date = models.DateField(auto_now=True)
    title = models.CharField(max_length=100, verbose_name='Название')
    text = models.TextField(verbose_name='Текст')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статью'
        verbose_name_plural = 'Статьи'

django_docker/article/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class AutUserForm(AuthenticationForm, forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'


class RegisterUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

django_docker/article/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView

from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Article
from .forms import ArticleForm, AutUserForm, RegisterUserForm


class ArticleListView(ListView):
    model = Article
    template_name = 'index.html'


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'detail.html'
    context_object_name = 'detail_page'


class MyProjectLoginView(LoginView):
    template_name = 'login.html'
    form_class = AutUserForm
    success_url = reverse_lazy('edit_page')

    def get_success_url(self):
        return self.success_url


class MyProjectLogout(LogoutView):
    next_page = reverse_lazy('edit_page')


class RegisterUserView(CreateView):
    model = User
    template_name = 'register_page.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('edit_page')
    success_msg = 'Пользователь успешно создан'

    def form_valid(self, form):
        form_valid = super().form_valid(form)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        aut_user = authenticate(username=username, password=password)
        login(self.request, aut_user)
        return form_valid

class CustomSuccessMessageMixin:
    @property
    def success_msg(self):
        return False

    def form_valid(self, form):
        messages.success(self.request, self.success_msg)
        return super().form_valid(form)

    def get_success_url(self):
        return '%s?id=%s' % (self.success_url, self.object.id)


class ArticleCreateView(CustomSuccessMessageMixin, CreateView):
    model = Article
    template_name = 'edit_page.html'
    form_class = ArticleForm
    success_url = reverse_lazy('edit_page')
    success_msg = 'Запись создана'

    def get_context_data(self, **kwargs):
        kwargs['list_articles'] = Article.objects.all().order_by('-id')
        return super().get_context_data(**kwargs)


class ArticleUpdateView(CustomSuccessMessageMixin, UpdateView):
    model = Article
    template_name = 'edit_page.html'
    form_class = ArticleForm
    success_url = reverse_lazy('edit_page')
    success_msg = 'Запись обновлена'

    def get_context_data(self, **kwargs):
        kwargs['update'] = True
        return super().get_context_data(**kwargs)


class ArticleDeleteView(CustomSuccessMessageMixin, DeleteView):
    model = Article
    template_name = 'edit_page.html'
    success_url = reverse_lazy('edit_page')
    success_msg = 'Запись удалена'

    def post(self, request, *args, **kwargs):
        messages.success(self.request, self.success_msg)
        return super().post(request)

# def edit_page(request):
#     success = False
#     if request.method == 'POST':
#         form = ArticleForm(request.POST)
#         if form.is_valid():
#             form.save()
#             success = True
#
#     template = 'edit_page.html'
#     context = {
#         'list_articles': Article.objects.all().order_by('-id'),
#         'form': ArticleForm(),
#         'success': success
#     }
#     return render(request, template, context)

#
# def update_page(request, pk):
#     get_article = Article.objects.get(pk=pk)
#     success_update = False
#
#     if request.method == 'POST':
#         form = ArticleForm(request.POST, instance=get_article)
#         if form.is_valid():
#             form.save()
#             success_update = True
#
#     template = 'edit_page.html'
#     context = {
#         'get_article': get_article,
#         'update': True,
#         'form': ArticleForm(instance=get_article),
#         'success_update': success_update
#     }
#     return render(request, template, context)

#
# def delete_page(request, pk):
#     get_article = Article.objects.get(pk=pk)
#     get_article.delete()
#     return redirect(reverse('edit_page'))

django_docker/templates/detail.html
{% extends 'index.html' %}

{% block content %}


        <a class="mt-4" href="/">вернуться назад</a>
    <h1 class="mt-4">{{ detail_page.title }}</h1>


       <h3>{{ i.title }}</h3>
        <li class="list-group-item">
           {{ detail_page.text }}<br>
            <b>{{ detail_page.create_date }}</b> <br>




{% endblock content %}

django_docker/templates/edit_page.html
{% extends 'index.html' %}

{% block content %}


    <a class="mt-5" href="/">вернуться назад</a>
    <h1 class="mt-4">Админ панель</h1>


    <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Добавить новую статью
</button>

    {% if success %}
        <p style="color:green">Запись добавлена</p>
    {% endif %}

    {% if messages %}
        <div class="alert alert-success">
            {% for m in messages %}
                {{ m }}
            {% endfor %}
        </div>
    {% endif %}

    {% if update %}
        <p class="mt-4">Страница редактирования</p>
         {% if success_update %}
            <p style="color:green">Запись обновлена</p>
        {% endif %}
        <a class="mt-4" href="{% url 'edit_page' %}">Предидущая страница</a>

         <form id="update_data"  method="post">
              {% csrf_token %}
              {{ form }}
          </form>
        <button form="update_data" type="submit" class="btn btn-primary">Сохранить</button>

    {% else %}

  <table class="table table-bordered mt-4">

  <thead>

    <tr>
      <th scope="col">id</th>
      <th scope="col">Название</th>
      <th scope="col">Текст</th>
      <th scope="col">Редактирование</th>
      <th scope="col">Удаление</th>
    </tr>
  </thead>
  <tbody>
  {% for i in list_articles %}
    <tr{% if i.id|slugify == request.GET.id %} style="background:#F6A81A" {% endif %}>
      <th scope="row">{{ i.id }}</th>
      <td>{{ i.title }}</td>
      <td>{{ i.text }}</td>
      <td><a href="{% url 'update_page' i.id %}">редактировать</a></td>
      <td>
          <form id="delete_form" action="{% url 'delete_page' i.id %}" method="post">{% csrf_token %}</form>
          <a href="javascript:void()" onclick='delete_question()'>удалить</a>
          <script>
              function delete_question() {
                    if (confirm('Вы уверены?')) {
                        document.getElementById('delete_form').submit()
                    }
              }
          </script>
      </td>
    </tr>
  {% endfor %}
  </tbody>

</table>
    {% endif %}

    <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Новая статья</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form id="add_form"  method="post">
              {% csrf_token %}
              {{ form }}
          </form>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
        <button form="add_form" type="submit" class="btn btn-primary">Сохранить</button>
      </div>
    </div>
  </div>
</div>



{% endblock content %}

django_docker/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>
<body>

<div class="container ">
    <ul class="nav nav-pills">
        <li class="nav-item">
            {% url 'article_list' as url_article_list %}

            <a class="nav-link {% if url_article_list == request.path %}active{% endif %}"
               href="{{ url_article_list }}">Главная</a>
        </li>
        <li class="nav-item">
            {% url 'edit_page' as url_edit_page %}
            <a class="nav-link {% if url_edit_page == request.path %}active{% endif %}" href="{{ url_edit_page }}">Создание/ред/удаление</a>
        </li>

        {% if request.user.is_authenticated %}
            <li class="nav-item ">
                {% url 'logout_page' as url_logout_page %}
                <a class="nav-link btn-danger ml-5" href="{{ url_logout_page }}">Выйти</a>
            </li>

        {% else %}
            <li class="nav-item">
                {% url 'login_page' as url_login_page %}
                <a class="nav-link {% if url_login_page == request.path %}active{% endif %}" href="{{ url_login_page }}"
                   href="{{ url_login_page }}">Авторизация</a>
            </li>
            <li class="nav-item">
                {% url 'register_page' as url_register_page %}
                <a class="nav-link {% if url_register_page == request.path %}active{% endif %}"
                   href="{{ url_register_page }}">Регистрация</a>
            </li>
            </li>
        {% endif %}

    {{ request.user }}
    </ul>


    {% block content %}
        <h1 class="mt-4"> Обзор статей</h1>
        {% for i in object_list %}
            <ul>
                <li><h3>{{ i.title }}</h3></li>
                <li class="list-group-item">
                    {{ i.text }}<br>
                    <a href="detail/{{ i.id }}">перейти к статье</a>
                </li>
                <li><b>{{ i.create_date }}</b></li>
            </ul>
        {% endfor %}
        </div>
    {% endblock content %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

django_docker/templates/login.html
{% extends 'index.html' %}

{% block content %}

        <h1>Авторизация</h1>
        <a class="mt-4" href="/">вернуться назад</a>

<div class="col-4">
<form id="add_form"  method="post">
              {% csrf_token %}
              {{ form }}
        <button form="add_form" type="submit" class="btn btn-primary mt-4">Войти</button>
          </form>


</div>




{% endblock content %}

django_docker/templates/register_page.html
{% extends 'index.html' %}

{% block content %}

        <h1>Регистрация</h1>
        <a class="mt-4" href="/">вернуться назад</a><br>


<div class="col-4">
<form id="add_form"  method="post">
              {% csrf_token %}
              {{ form }}

          </form>
<button form="add_form" type="submit" class="btn btn-primary mt-4">Зарегистрироваться</button>


</div>

{% endblock content %}